package com.example;

/**
 * システムメッセージを管理する列挙型クラスです。
 * 
 * @author atagawa
 * @since 1.0.0d 2018/05/23
 *
 */
public enum MessageType {
    INFMSG_DEFAULT_SPETIAL_CHARS,
    INFMSG_IGNORE_SPETIAL_CHAR_OPERATION,
    ERRMSG_INPUT_NON_SPECIAL_CHAR,
    ERRMSG_NUMBER_FORMAT,
    ERRMSG_NO_SUCH_ALGORITHM,
    ERRMSG_ARRAY_INDEX_OUT_OF_BOUNDS,
    ERRMSG_OVER_RANGE_VALUE,
    ERRMSG_OVER_PASSWORD_LENGTH,
    ERRMSG_UNEXPECTED_ARGUMENTS,
    ERRMSG_INPUT_INCOMPATIBLE_VALUE;
}
